import java.util.ArrayList;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
        Review rev1 = new Review("Mousa", 5.0, "Absolutely loved it! The plot was engaging.");
        Review rev2 = new Review("Omar", 4.8, "Great read, but the ending felt rushed.");
        Review rev3 = new Review("Fatima", 3.5, "It was okay, some parts dragged on too long.");
        Review rev4 = new Review("Ali", 4.0, "Interesting characters, but needed more depth.");
        Review rev5 = new Review("Nora", 2.0, "I didn't enjoy it; it was hard to follow.");
        Review rev6 = new Review("Samir", 4.7, "Well-written and thought-provoking!");
        Review rev7 = new Review("Layla", 3.0, "Average story, not what I expected.");
        Review rev8 = new Review("Hassan", 5.0, "An instant classic! Highly recommend.");
        Review rev9 = new Review("Yasmin", 4.2, "Good story, but I wanted more action.");
        Review rev10 = new Review("Khaled", 1.5, "Did not like the characters; they were unlikable.");
        Review rev11 = new Review("Mariam", 4.4, "Enjoyable, with some surprising twists.");
        Review rev12 = new Review("Rami", 3.8, "Good, but some chapters were slow.");
        Review rev13 = new Review("Jamal", 2.5, "It had potential, but didn't deliver.");
        Review rev14 = new Review("Huda", 4.9, "Incredible storytelling! A must-read.");
        Review rev15 = new Review("Sami", 3.6, "It was decent, but I've read better.");
        ArrayList<Review> review1 = new ArrayList<>();
        review1.add(rev1); review1.add(rev2); review1.add(rev8); review1.add(rev14); review1.add(rev11);
        ArrayList<Review> review2 = new ArrayList<>();
        review2.add(rev3); review2.add(rev9); review2.add(rev13); review2.add(rev14); review2.add(rev12);
        ArrayList<Review> review3 = new ArrayList<>();
        review3.add(rev11); review3.add(rev3); review3.add(rev4); review3.add(rev14); review3.add(rev10);
        ArrayList<Review> review4 = new ArrayList<>();
        review4.add(rev12); review4.add(rev15); review4.add(rev2); review4.add(rev10); review4.add(rev8);
        Book book1 = new Book(92, review1, "Ahmed", "34434839439851", 50, "Book 1");
        Book book2 = new Book(100, review4, "Fatima", "32832832329332", 60, "Book 2");
        Book book3 = new Book(54, review3, "Ali", "9678784848747", 55, "Book 3");
        Book book4 = new Book(38, review3, "Maryam", "434399936699233", 45, "Book 4");
        Book book5 = new Book(1005, review1, "Yuosuf", "5454424242332", 70, "Book 5");
        Book book6 = new Book(43, review2, "Aisha", "4994302023233", 80, "Book 6");
        Book book7 = new Book(52, review2, "Omar", "34434839439857", 90, "Book 7");
        Book book8 = new Book(431, review1, "Leila", "4438494980232", 40, "Book 8");
        Book book9 = new Book(20, review3, "Hassan", "4948439843004", 30, "Book 9");
        Book book10 = new Book(95, review4, "Sara", "9886665217832", 75, "Book 10");
        System.out.println(book1.getAverage());
        System.out.println(book1.getMediaType());
        System.out.println(book1.getReview());
        System.out.println(book1.isBestseller());
        book1.addReview(new Review("Basil",2.9,"bad idea"));
        System.out.println(book1.getReview());
        System.out.println(book1.getStock());
        book1.reStock(35);
        System.out.println(book1.getStock());
        book7.reStock(500);
        System.out.println(book7.getStock());
        System.out.println(book8.getMediaType());
        System.out.println(book9.getMediaType());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        Music music1 = new Music("Ahmed", "12345678901", 120, "Music-1", "Khaled");
        Music music2 = new Music("Sara", "23456789012", 150, "Music-2", "Laila");
        Music music3 = new Music("Omar", "34567890123", 200, "Music-3", "Hassan");
        Music music4 = new Music("Nada", "45678901234", 130, "Music-4", "Khaled");
        Music music5 = new Music("Rania", "56789012345", 160, "Music-5", "Fahad");
        Music music6 = new Music("Mona", "67890123456", 110, "Music-6", "Mansour");
        Music music7 = new Music("Fadi", "78901234567", 180, "Music-7", "Hadi");
        Music music8 = new Music("Salim", "89012345678", 140, "Music-8", "Saad");
        Music music9 = new Music("Layla", "90123456789", 190, "Music-9", "Khaled");
        Music music10 = new Music("Tariq", "01234567890", 125, "Music-10", "Noura");
        ArrayList<Music> arr = new ArrayList<>();
        arr.add(music1); arr.add(music2); arr.add(music3); arr.add(music4); arr.add(music5); arr.add(music6);
        System.out.println(music1.generalPlayList(arr));
        System.out.println(music7.generalPlayList(arr));
        System.out.println(music7.getMediaType());
        System.out.println(music10.getMediaType());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        Movie movie1 = new Movie("Yousef", "32389239823", 50.0, "Movie-1", 120);
        Movie movie2 = new Movie("Fatima", "12103284373", 29.0, "Movie-2", 135);
        Movie movie3 = new Movie("Hassan", "39883982398", 32, "Movie-3", 110);
        Movie movie4 = new Movie("Amina", "32983298932", 180.0, "Movie-4", 140);
        Movie movie5 = new Movie("Ali", "32392993832", 70.0, "Movie-5", 315);
        Movie movie6 = new Movie("Mariam", "664334344366", 45.0, "Movie-6", 130);
        Movie movie7 = new Movie("Omar", "21982121982", 200.0, "Movie-7", 150);
        Movie movie8 = new Movie("Yousef", "3932329883", 52.0, "Movie-8", 240);
        Movie movie9 = new Movie("Saif", "3232392323", 100.0, "Movie-9", 200);
        Movie movie10 = new Movie("Yousef", "32323281101", 25.0, "Movie-10", 105);
        ArrayList<Movie> arr1 = new ArrayList<>();
        arr1.add(movie1); arr1.add(movie2); arr1.add(movie3); arr1.add(movie4); arr1.add(movie5); arr1.add(movie6);
        arr1.add(movie7); arr1.add(movie8); arr1.add(movie9);arr1.add(movie10);
        System.out.println(movie1.recommenSimilarMovies(arr1));
        System.out.println(movie5.recommenSimilarMovies(arr1));
        System.out.println(movie1.getDuration());
        System.out.println(movie1.getMediaType());
        System.out.println(movie2.getMediaType());
        System.out.println(movie3.getMediaType());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        ArrayList<Media> purchaseMediaList1 = new ArrayList<>();
        ArrayList<Media> shopingCart1 = new ArrayList<>();
        ArrayList<Media> purchaseMediaList2 = new ArrayList<>();
        ArrayList<Media> shopingCart2 = new ArrayList<>();
        ArrayList<Media> purchaseMediaList3 = new ArrayList<>();
        ArrayList<Media> shopingCart3 = new ArrayList<>();
        ArrayList<Media> purchaseMediaList4 = new ArrayList<>();
        ArrayList<Media> shopingCart4 = new ArrayList<>();
        ArrayList<Media> purchaseMediaList5 = new ArrayList<>();
        ArrayList<Media> shopingCart5 = new ArrayList<>();
        User user1 = new User("sasasssa@hotmail.com",purchaseMediaList1,shopingCart1,"h-baroom");
        User user2 = new User("fiasl@example.com", purchaseMediaList2, shopingCart2, "fas");
        User user3 = new User("ali@example.com", purchaseMediaList3, shopingCart3, "a-effd21");
        User user4 = new User("mohammed@example.com", purchaseMediaList4, shopingCart4, "sas");
        User user5 = new User("elias@example.com", purchaseMediaList5, shopingCart5, "el92");
        user1.addToCart(book1);
        System.out.println(user1.getPurchaseMediaList());
        System.out.println(user1.getShoppingCart());
        user1.checkout();
        System.out.println(user1.getPurchaseMediaList());
        System.out.println(user1.getShoppingCart());
        System.out.println("*******************************************");
        music10.listen(user1);
        System.out.println(user1.getPurchaseMediaList());
        System.out.println("*******************************************");
        user5.addToCart(movie3);
        user5.addToCart(book7);
        user5.addToCart(music9);
        user5.addToCart(book2);
        user5.addToCart(music6);
        user5.addToCart(movie9);
        user5.addToCart(book4);
        user5.addToCart(movie6);
        user5.removeFromCart(music9);
        user5.removeFromCart(movie3);
        user5.removeFromCart(book7);
        System.out.println(user5.getShoppingCart());
        System.out.println("*******************************************");
        user3.addToCart(music9);
        user3.addToCart(book2);
        user3.addToCart(music6);
        user3.addToCart(movie9);
        user3.addToCart(book4);
        user3.addToCart(movie6);
        user3.removeFromCart(music9);
        user3.removeFromCart(movie3);
        user3.removeFromCart(book4);
        System.out.println(user3.getPurchaseMediaList());
        System.out.println(user3.getShoppingCart());
        user3.checkout();
        System.out.println(user3.getPurchaseMediaList());
        System.out.println(user3.getShoppingCart());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        ArrayList<User> arr2 = new ArrayList<>();
        arr2.add(user1); arr2.add(user2); arr2.add(user3);arr2.add(user5);
        ArrayList<Media> arr3 = new ArrayList<>();
        arr3.add(book5); arr3.add(movie2); arr3.add(book4); arr3.add(book9); arr3.add(book8);arr3.add(movie7); arr3.add(book3);
        arr3.add(music9); arr3.add(book2); arr3.add(music2); arr3.add(book3);
        Store store1 =new Store(arr3,arr2);
        store1.dispalyMedias();
        store1.dispalyUser();
        store1.searchBook("Book 5");
        store1.searchBook("Book11");
        store1.searchBook("Book5");
        ArrayList<Media> purchaseMediaList6 = new ArrayList<>();
        ArrayList<Media> shopingCart6 = new ArrayList<>();
        store1.addUser(new User("add_example.com", purchaseMediaList6, shopingCart6, "zro5454"));
        store1.dispalyUser();
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        ArrayList<Media> purchaseMediaList7 = new ArrayList<>();
        ArrayList<Media> shopingCart7 = new ArrayList<>();
        User user7 = new User("watch-listen-purchase@example.com", purchaseMediaList7, shopingCart7, "WLP123");
        movie1.watch(user7);
        music2.listen(user7);
        book8.purchase(user7);
        book6.purchase(user7);
        System.out.println(user7.getPurchaseMediaList());
        System.out.println(user7.getShoppingCart());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        Media media = new Media("Faisal", "1832494433", 220, "music-22");
        System.out.println(media.getAuteur());
        System.out.println(media.getMediaType());
        System.out.println(media.getISBN());
        System.out.println(media.getTitle());
        System.out.println(media.getPrice());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        Novel novel1 = new Novel("noval1 : ",review1);
        System.out.print(novel1.getGenre());
        System.out.println(novel1.getMediaType());
        Novel novel2 = new Novel("noval2 : ",review2);
        System.out.print(novel2.getGenre());
        System.out.println(novel2.getMediaType());
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        AcademicBook academicBook1 = new AcademicBook("academicBook1 : ",review1);
        System.out.print(academicBook1.getSubject());
        System.out.println(academicBook1.getMediaType());
        AcademicBook academicBook2 = new AcademicBook("academicBook2 : ",review2);
        System.out.print(academicBook2.getSubject());
        System.out.println(academicBook2.getMediaType());






    }
}